import type { SeedCollection } from './types'

export const SEED_COLLECTIONS: SeedCollection[] = [
  {
    slug: 'start-here',
    title: 'Start here',
    subtitle: 'Twelve sites that explain what this place is for',
    description:
      'If you have never browsed a directory before, start with these. Each one is the kind of site people bookmark and quietly use for years — useful, generous, and made by someone who cared.',
    hue: 262,
    sites: [
      'https://neal.fun',
      'https://ourworldindata.org',
      'https://ciechanow.ski',
      'https://radio.garden',
      'https://publicdomainreview.org',
      'https://lichess.org',
      'https://standardebooks.org',
      'https://explorabl.es',
      'https://earth.nullschool.net',
      'https://squoosh.app',
      'https://www.rijksmuseum.nl',
      'https://kottke.org',
    ],
  },
  {
    slug: 'tools-that-respect-your-time',
    title: 'Tools that respect your time',
    subtitle: 'No account, no upsell, no cookie wall',
    description:
      'Single-purpose utilities that load instantly, do the job, and let you leave. The web used to be full of these. It still is, if you know where to look.',
    hue: 200,
    sites: [
      'https://squoosh.app',
      'https://crontab.guru',
      'https://explainshell.com',
      'https://time.is',
      'https://regex101.com',
      'https://www.diffchecker.com',
      'https://justtherecipe.com',
      'https://www.worldtimebuddy.com',
      'https://httpstat.us',
      'https://tldr.sh',
    ],
  },
  {
    slug: 'explain-it-visually',
    title: 'Explain it to me visually',
    subtitle: 'Ideas you can drag, poke and break',
    description:
      'The best teaching on the internet is interactive. These sites let you change a variable and watch the consequence, which is worth a hundred paragraphs.',
    hue: 32,
    sites: [
      'https://ciechanow.ski',
      'https://ncase.me',
      'https://explorabl.es',
      'https://setosa.io',
      'https://distill.pub',
      'https://www.thetruesize.com',
      'https://learningmusic.ableton.com',
      'https://eyes.nasa.gov',
      'https://musiclab.chromeexperiments.com',
      'https://sandspiel.club',
    ],
  },
  {
    slug: 'free-libraries-of-the-world',
    title: 'Free libraries of the world',
    subtitle: 'Institutions giving away their collections',
    description:
      'Museums, national libraries and archives that digitised everything and then, remarkably, let you have it. Most of this is public domain and free to reuse.',
    hue: 240,
    sites: [
      'https://www.gutenberg.org',
      'https://standardebooks.org',
      'https://www.rijksmuseum.nl',
      'https://www.metmuseum.org',
      'https://www.loc.gov',
      'https://www.europeana.eu',
      'https://openlibrary.org',
      'https://publicdomainreview.org',
      'https://www.artic.edu',
      'https://www.oldbookillustrations.com',
      'https://www.bl.uk',
    ],
  },
  {
    slug: 'the-web-at-its-weirdest',
    title: 'The web at its weirdest',
    subtitle: 'Gloriously unnecessary',
    description:
      'Sites that exist for no reason at all. Someone bought a domain, built the joke, and paid the renewal fee every year since. This is the good internet.',
    hue: 55,
    sites: [
      'https://theuselessweb.com',
      'https://pointerpointer.com',
      'https://eelslap.com',
      'https://www.cat-bounce.com',
      'https://papertoilet.com',
      'https://puginarug.com',
      'https://isitchristmas.com',
      'https://findtheinvisiblecow.com',
      'https://omfgdogs.com',
      'https://www.windows93.net',
      'https://hackertyper.net',
      'https://koalastothemax.com',
    ],
  },
  {
    slug: 'sunday-afternoon-rabbit-holes',
    title: 'Sunday afternoon rabbit holes',
    subtitle: 'Enter at your own risk',
    description:
      'You will open one of these meaning to spend five minutes on it. Set a timer. We are not responsible for the rest of your day.',
    hue: 300,
    sites: [
      'https://www.atlasobscura.com',
      'https://everynoise.com',
      'https://radiooooo.com',
      'https://www.whosampled.com',
      'https://www.etymonline.com',
      'https://oldweb.today',
      'https://www.wikiart.org',
      'https://www.randomstreetview.com',
      'https://www.flightradar24.com',
      'https://www.metafilter.com',
    ],
  },
  {
    slug: 'type-and-letterform',
    title: 'Type & letterform',
    subtitle: 'For people who notice kerning',
    description:
      'Foundries, specimens, archives and one complete free book on typography. Most of these will also improve how you look at every other website.',
    hue: 330,
    sites: [
      'https://practicaltypography.com',
      'https://fontsinuse.com',
      'https://www.typewolf.com',
      'https://klim.co.nz',
      'https://velvetyne.fr',
      'https://collletttivo.it',
      'https://www.fontshare.com',
      'https://fonts.google.com',
      'https://standardebooks.org',
    ],
  },
  {
    slug: 'quiet-corners',
    title: 'Quiet corners',
    subtitle: 'Somewhere to put your attention down',
    description:
      'No feed, no notifications, nothing to achieve. Open one of these when the rest of the internet has become too loud.',
    hue: 165,
    sites: [
      'https://www.rainymood.com',
      'https://asoftmurmur.com',
      'https://musicforprogramming.net',
      'https://pixelthoughts.co',
      'https://www.donothingfor2minutes.com',
      'https://weavesilk.com',
      'https://zoomquilt.org',
      'https://readsomethingwonderful.com',
      'https://www.thisisnothing.com',
    ],
  },
  {
    slug: 'the-small-web',
    title: 'The small web',
    subtitle: 'Made by a person, not a company',
    description:
      'Personal sites, hand-built pages and the infrastructure that keeps them alive. Slower, stranger and far more interesting than the platforms.',
    hue: 100,
    sites: [
      'https://neocities.org',
      'https://kottke.org',
      'https://paulgraham.com',
      'https://danluu.com',
      'https://craigmod.com',
      'https://tildes.net',
      'https://search.marginalia.nu',
      'https://tinyprojects.dev',
      'https://www.dwitter.net',
      'http://www.textfiles.com',
    ],
  },
  {
    slug: 'numbers-you-can-trust',
    title: 'Numbers you can trust',
    subtitle: 'Primary sources and honest charts',
    description:
      'When you need the actual figure rather than someone’s summary of it. Every one of these shows its working and lets you download the data.',
    hue: 190,
    sites: [
      'https://ourworldindata.org',
      'https://data.gov',
      'https://datausa.io',
      'https://arxiv.org',
      'https://www.quantamagazine.org',
      'https://observablehq.com',
      'https://www.levels.fyi',
      'https://portfoliocharts.com',
      'https://www.propublica.org',
    ],
  },
  {
    slug: 'cook-something-better-tonight',
    title: 'Cook something better tonight',
    subtitle: 'Recipes from people who test them properly',
    description:
      'No fifteen-hundred-word preamble about a trip to Tuscany. These are sites run by people who cook the dish repeatedly, write down what goes wrong, and tell you why.',
    hue: 24,
    sites: [
      'https://www.seriouseats.com',
      'https://www.kingarthurbaking.com',
      'https://www.maangchi.com',
      'https://www.justonecookbook.com',
      'https://smittenkitchen.com',
      'https://food52.com',
      'https://thewoksoflife.com',
      'https://minimalistbaker.com',
      'https://www.davidlebovitz.com',
      'https://www.budgetbytes.com',
    ],
  },
  {
    slug: 'maps-worth-getting-lost-in',
    title: 'Maps worth getting lost in',
    subtitle: 'Cartography as a place to spend an evening',
    description:
      'Some of these are useful. Most are just beautiful. All of them reward zooming in further than you meant to.',
    hue: 165,
    sites: [
      'https://www.openstreetmap.org',
      'https://oldmapsonline.org',
      'https://www.davidrumsey.com',
      'https://earth.nullschool.net',
      'https://www.ventusky.com',
      'https://www.lightpollutionmap.info',
      'https://opentopomap.org',
      'https://www.shadowmap.org',
      'https://www.thetruesize.com',
      'https://www.openrailwaymap.org',
    ],
  },
  {
    slug: 'money-explained-honestly',
    title: 'Money, explained honestly',
    subtitle: 'Nobody here is selling you a product',
    description:
      'Personal finance is full of people paid to give advice. These are the sites that show their working, publish the data, and mostly tell you to do something boring.',
    hue: 100,
    sites: [
      'https://www.bogleheads.org',
      'https://ofdollarsanddata.com',
      'https://portfoliocharts.com',
      'https://www.mrmoneymustache.com',
      'https://www.investopedia.com',
      'https://www.levels.fyi',
      'https://80000hours.org',
      'https://www.morningstar.com',
    ],
  },
  {
    slug: 'move-sleep-breathe',
    title: 'Move, sleep, breathe',
    subtitle: 'Health without the supplement funnel',
    description:
      'Evidence-based, mostly non-commercial, and written to be read rather than to sell. Includes the two national health services that publish the calmest medical writing anywhere.',
    hue: 350,
    sites: [
      'https://www.nhs.uk',
      'https://medlineplus.gov',
      'https://nutritionfacts.org',
      'https://www.strongerbyscience.com',
      'https://examine.com',
      'https://exrx.net',
      'https://darebee.com',
      'https://www.helpguide.org',
      'https://www.sleepfoundation.org',
    ],
  },
  {
    slug: 'primary-sources',
    title: 'Primary sources',
    subtitle: 'Go and look at the actual thing',
    description:
      'Encyclopedias that cite, archives that scan, and databases that let you download the raw file. For when a summary of a summary will not do.',
    hue: 240,
    sites: [
      'https://plato.stanford.edu',
      'https://oeis.org',
      'https://www.biodiversitylibrary.org',
      'https://www.loc.gov',
      'https://www.si.edu',
      'https://www.archives.gov',
      'https://www.nationalarchives.gov.uk',
      'https://arxiv.org',
      'https://www.worldcat.org',
      'https://digitalcollections.nypl.org',
    ],
  },
  {
    slug: 'show-me-the-data',
    title: 'Show me the data',
    subtitle: 'Visual journalism and honest charts',
    description:
      'People who take a large dataset and make it mean something, without torturing the axis. Several of these will change how you read every other chart.',
    hue: 190,
    sites: [
      'https://ourworldindata.org',
      'https://pudding.cool',
      'https://flowingdata.com',
      'https://informationisbeautiful.net',
      'https://www.visualcapitalist.com',
      'https://observablehq.com',
      'https://datausa.io',
      'https://setosa.io',
    ],
  },
]
